lr_actor: 0.002
lr_critic: 0.05
K_epochs: 40
eps_clip: 0.3
entropy_coef: 0.1
mse_coef: 0.65
gamma: 0.9923157316342434

policy:
  
  actor:
    n_hidden_layers_actor: 4
    hidden_size_actor: 128
  
  critic:
    n_hidden_layers_critic: 4
    hidden_size_critic: 128